// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TetePizza.Data;

#nullable disable

namespace BankApp.Data.Migrations
{
    [DbContext(typeof(PizzaContext))]
    [Migration("20240213212304_InitialPrueba")]
    partial class InitialPrueba
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("TetePizza.Models.Ingrediente", b =>
                {
                    b.Property<int>("IngredienteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IngredienteId"), 1L, 1);

                    b.Property<string>("NombreIngrediente")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(150)");

                    b.Property<string>("Origen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PizzaId")
                        .HasColumnType("int");

                    b.HasKey("IngredienteId");

                    b.HasIndex("PizzaId");

                    b.ToTable("Ingrediente");

                    b.HasData(
                        new
                        {
                            IngredienteId = 1,
                            NombreIngrediente = "Champiñon",
                            Origen = "Vegetal",
                            PizzaId = 1
                        },
                        new
                        {
                            IngredienteId = 2,
                            NombreIngrediente = "Oliva",
                            Origen = "Vegetal",
                            PizzaId = 2
                        },
                        new
                        {
                            IngredienteId = 3,
                            NombreIngrediente = "Piña",
                            Origen = "Vegetal",
                            PizzaId = 1
                        },
                        new
                        {
                            IngredienteId = 4,
                            NombreIngrediente = "Pollo",
                            Origen = "Animal",
                            PizzaId = 2
                        });
                });

            modelBuilder.Entity("TetePizza.Models.Pizza", b =>
                {
                    b.Property<int?>("PizzaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("PizzaID"), 1L, 1);

                    b.Property<string>("IsGlutenFree")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PizzaID");

                    b.ToTable("Pizza");

                    b.HasData(
                        new
                        {
                            PizzaID = 1,
                            IsGlutenFree = "Yes",
                            Nombre = "John Doe"
                        },
                        new
                        {
                            PizzaID = 2,
                            IsGlutenFree = "Yes",
                            Nombre = "Jane Doe"
                        },
                        new
                        {
                            PizzaID = 3,
                            IsGlutenFree = "No",
                            Nombre = "Ivan Badia"
                        });
                });

            modelBuilder.Entity("TetePizza.Models.Ingrediente", b =>
                {
                    b.HasOne("TetePizza.Models.Pizza", "Pizza")
                        .WithMany("ingredientes")
                        .HasForeignKey("PizzaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pizza");
                });

            modelBuilder.Entity("TetePizza.Models.Pizza", b =>
                {
                    b.Navigation("ingredientes");
                });
#pragma warning restore 612, 618
        }
    }
}
